// <auto-generated />
using System;
using System.Text.Json;
using FinanzasInteligentes.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanzasInteligentes.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20260725174206_M0011_MovimientosRecurrentes")]
    partial class M0011_MovimientosRecurrentes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CajaCompartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Saldo")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId")
                        .IsUnique();

                    b.ToTable("cajas_compartidas", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CategoriaFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("PK_familias_categorias");

                    b.HasIndex("GrupoFamiliarId", "Nombre")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("categorias", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CuentaCompartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("CompartidaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("compartida_por_usuario_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("GrupoFamiliarId", "CuentaId")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("cuentas_compartidas", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.EliminacionGrupoFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("ErrorCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId")
                        .IsUnique()
                        .HasFilter("estado = 'pendiente'");

                    b.ToTable("eliminaciones", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("grupos_familiares", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.IntegranteFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("GrupoFamiliarId", "UsuarioId")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("integrantes", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.InvitacionFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Correo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<string>("HashCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_codigo");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_token");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<Guid?>("UsuarioDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_destino_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("HashToken")
                        .IsUnique();

                    b.ToTable("invitaciones", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.MovimientoFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.PrimitiveCollection<Guid[]>("CategoriaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("categoria_ids");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("PK_familias_movimientos");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("IX_familias_movimientos_cuenta_id");

                    b.HasIndex("GrupoFamiliarId", "Fecha", "Id");

                    b.ToTable("movimientos", "familias", t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_familiares_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.OperacionCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaPrivadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_privada_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<long>("SaldoAnterior")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo_anterior");

                    b.Property<long>("SaldoPosterior")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo_posterior");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPrivadaId");

                    b.HasIndex("GrupoFamiliarId");

                    b.ToTable("operaciones_caja", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.PresupuestoFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.PrimitiveCollection<Guid[]>("CategoriaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("categoria_ids");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<Guid>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodo");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId");

                    b.ToTable("presupuestos", "familias");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.AporteMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AportadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("aportado_por");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_origen_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("HashIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_idempotencia");

                    b.Property<Guid>("MetaAhorroId")
                        .HasColumnType("uuid")
                        .HasColumnName("meta_id");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.HasIndex("AportadoPor");

                    b.HasIndex("CuentaOrigenId");

                    b.HasIndex("MetaAhorroId", "HashIdempotencia")
                        .IsUnique();

                    b.HasIndex("MetaAhorroId", "Fecha", "Id");

                    b.ToTable("aportes_meta", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_aportes_meta_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("boolean")
                        .HasColumnName("es_predeterminada");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("categorias", "finanzas");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<bool>("IncluidaEnTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("incluida_en_total");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<long>("SaldoActual")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo_actual");

                    b.Property<long>("SaldoInicial")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("cuentas", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_cuentas_moneda", "moneda = 'PYG'");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.MetaAhorro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ambito");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaObjetivo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_objetivo");

                    b.Property<Guid?>("GrupoFamiliarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_familiar_id");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("MontoObjetivo")
                        .HasColumnType("bigint")
                        .HasColumnName("monto_objetivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("CuentaId");

                    b.HasIndex("GrupoFamiliarId", "Estado");

                    b.HasIndex("UsuarioId", "Estado");

                    b.ToTable("metas_ahorro", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_metas_ahorro_moneda", "moneda = 'PYG'");

                            t.HasCheckConstraint("ck_metas_ahorro_monto", "monto_objetivo > 0");

                            t.HasCheckConstraint("ck_metas_ahorro_propietario", "(ambito = 'privado' AND usuario_id IS NOT NULL AND grupo_familiar_id IS NULL) OR (ambito = 'familiar' AND usuario_id IS NULL AND grupo_familiar_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnuladoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anulado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<DateOnly?>("PeriodoRecurrencia")
                        .HasColumnType("date")
                        .HasColumnName("periodo_recurrencia");

                    b.Property<Guid?>("RecurrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurrencia_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("RecurrenciaId", "PeriodoRecurrencia")
                        .IsUnique()
                        .HasFilter("recurrencia_id IS NOT NULL");

                    b.HasIndex("UsuarioId", "Fecha", "Id");

                    b.ToTable("movimientos", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_moneda", "moneda = 'PYG'");

                            t.HasCheckConstraint("ck_movimientos_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.MovimientoRecurrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("CantidadOcurrencias")
                        .HasColumnType("bigint")
                        .HasColumnName("cantidad_ocurrencias");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frecuencia");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<long>("OcurrenciasCompletadas")
                        .HasColumnType("bigint")
                        .HasColumnName("ocurrencias_completadas");

                    b.Property<DateOnly>("ProximaEjecucion")
                        .HasColumnType("date")
                        .HasColumnName("proxima_ejecucion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset?>("UltimaEjecucionEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_ejecucion_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("Estado", "ProximaEjecucion");

                    b.HasIndex("UsuarioId", "CuentaId", "Descripcion")
                        .IsUnique()
                        .HasFilter("estado = 'activa' AND eliminado_en IS NULL");

                    b.ToTable("recurrencias", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_recurrencias_fechas", "fecha_fin IS NULL OR fecha_fin >= fecha_inicio");

                            t.HasCheckConstraint("ck_recurrencias_frecuencia", "frecuencia IN ('diaria', 'semanal', 'quincenal', 'mensual', 'anual')");

                            t.HasCheckConstraint("ck_recurrencias_moneda", "moneda = 'PYG'");

                            t.HasCheckConstraint("ck_recurrencias_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Presupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("Monto")
                        .HasColumnType("bigint")
                        .HasColumnName("monto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("PK_presupuestos1");

                    b.HasIndex("UsuarioId", "Estado");

                    b.ToTable("presupuestos", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_presupuestos_moneda", "moneda = 'PYG'");

                            t.HasCheckConstraint("ck_presupuestos_monto", "monto > 0");

                            t.HasCheckConstraint("ck_presupuestos_periodo", "periodo IN ('semanal', 'mensual', 'anual')");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.TarjetaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("CuentaPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_pago_id");

                    b.Property<long>("DiaCierre")
                        .HasColumnType("bigint")
                        .HasColumnName("dia_cierre");

                    b.Property<long>("DiaVencimiento")
                        .HasColumnType("bigint")
                        .HasColumnName("dia_vencimiento");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("emisor");

                    b.Property<long>("LimiteCredito")
                        .HasColumnType("bigint")
                        .HasColumnName("limite_credito");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<long>("SaldoUtilizado")
                        .HasColumnType("bigint")
                        .HasColumnName("saldo_utilizado");

                    b.Property<string>("UltimosCuatro")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("ultimos_cuatro");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPagoId");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("tarjetas_credito", "finanzas", t =>
                        {
                            t.HasCheckConstraint("ck_tarjetas_credito_dias", "dia_cierre BETWEEN 1 AND 31 AND dia_vencimiento BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_tarjetas_credito_limites", "limite_credito >= 0 AND saldo_utilizado >= 0");

                            t.HasCheckConstraint("ck_tarjetas_credito_moneda", "moneda = 'PYG'");
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.DesafioOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destino");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_codigo");

                    b.Property<int>("IntentosRestantes")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_restantes");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset?>("VerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificado_en");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("desafios_otp", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.EliminacionPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("ErrorCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("estado = 'pendiente'");

                    b.ToTable("eliminaciones_perfil", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.PreferenciasUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("NotificacionesCorreo")
                        .HasColumnType("boolean")
                        .HasColumnName("notificaciones_correo");

                    b.Property<bool>("NotificacionesPush")
                        .HasColumnType("boolean")
                        .HasColumnName("notificaciones_push");

                    b.Property<bool>("ResumenSemanal")
                        .HasColumnType("boolean")
                        .HasColumnName("resumen_semanal");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tema");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("UsuarioId");

                    b.ToTable("preferencias", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.RecuperacionContrasena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumido_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("HashToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("recuperaciones_contrasena", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("FamiliaToken")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_token");

                    b.Property<string>("HashRefreshToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_refresh_token");

                    b.Property<string>("IdentificadorDispositivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identificador_dispositivo");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_dispositivo");

                    b.Property<string>("PlataformaDispositivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plataforma_dispositivo");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("HashRefreshToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesiones", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("AnonimizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonimizado_en");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("idioma");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("ubicacion");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("anonimizado_en IS NULL");

                    b.ToTable("usuarios", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.VerificacionOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumido_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid")
                        .HasColumnName("desafio_id");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("verificaciones_otp", "identidad");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Infraestructura.Entidades.EventoOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgregadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agregado_id");

                    b.Property<string>("AgregadoTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agregado_tipo");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset>("DisponibleEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disponible_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "DisponibleEn");

                    b.ToTable("outbox_eventos", "infra");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Infraestructura.Entidades.Idempotencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<short?>("CodigoRespuesta")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_respuesta");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<JsonDocument>("CuerpoRespuesta")
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo_respuesta");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashSolicitud")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_solicitud");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ruta");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Clave")
                        .IsUnique()
                        .HasFilter("usuario_id IS NOT NULL");

                    b.ToTable("idempotencias", "infra");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Suscripciones.PlanSuscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.PrimitiveCollection<string[]>("Capacidades")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capacidades");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .HasColumnType("boolean")
                        .HasColumnName("destacado");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodicidad");

                    b.Property<long>("Precio")
                        .HasColumnType("bigint")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("planes", "suscripciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Activo = true,
                            Capacidades = new[] { "cuentas", "categorias", "movimientos" },
                            Codigo = "gratis",
                            CreadoEn = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descripcion = "Funciones esenciales de finanzas personales.",
                            Destacado = false,
                            Moneda = "PYG",
                            Nombre = "Gratis",
                            Periodo = "sin-vencimiento",
                            Precio = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Activo = true,
                            Capacidades = new[] { "ocr", "predicciones", "exportaciones", "alertas-prioritarias" },
                            Codigo = "premium-mensual",
                            CreadoEn = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descripcion = "Todas las capacidades premium con renovación mensual.",
                            Destacado = true,
                            Moneda = "PYG",
                            Nombre = "Premium mensual",
                            Periodo = "mensual",
                            Precio = 45000L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Activo = true,
                            Capacidades = new[] { "ocr", "predicciones", "exportaciones", "alertas-prioritarias" },
                            Codigo = "premium-anual",
                            CreadoEn = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descripcion = "Todas las capacidades premium con renovación anual.",
                            Destacado = false,
                            Moneda = "PYG",
                            Nombre = "Premium anual",
                            Periodo = "anual",
                            Precio = 450000L
                        });
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Suscripciones.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("CanceladaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelada_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FinPeriodoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_periodo_en");

                    b.Property<string>("HashComprobante")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_comprobante");

                    b.Property<DateTimeOffset>("IniciadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_en");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proveedor");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("estado IN ('activa', 'en_gracia')");

                    b.HasIndex("Proveedor", "HashComprobante")
                        .IsUnique();

                    b.ToTable("suscripciones", "suscripciones", t =>
                        {
                            t.HasCheckConstraint("ck_suscripciones_periodo", "fin_periodo_en > iniciada_en");
                        });
                });

            modelBuilder.Entity("MovimientoCategoria", b =>
                {
                    b.Property<Guid>("movimiento_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoria_id")
                        .HasColumnType("uuid");

                    b.HasKey("movimiento_id", "categoria_id");

                    b.HasIndex("categoria_id");

                    b.ToTable("movimientos_categorias", "finanzas");
                });

            modelBuilder.Entity("PresupuestoCategoria", b =>
                {
                    b.Property<Guid>("presupuesto_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoria_id")
                        .HasColumnType("uuid");

                    b.HasKey("presupuesto_id", "categoria_id");

                    b.HasIndex("categoria_id");

                    b.ToTable("presupuesto_categorias", "finanzas");
                });

            modelBuilder.Entity("RecurrenciaCategoria", b =>
                {
                    b.Property<Guid>("recurrencia_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoria_id")
                        .HasColumnType("uuid");

                    b.HasKey("recurrencia_id", "categoria_id");

                    b.HasIndex("categoria_id");

                    b.ToTable("recurrencia_categorias", "finanzas");
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CajaCompartida", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithOne()
                        .HasForeignKey("FinanzasInteligentes.Dominio.FinanzasFamiliares.CajaCompartida", "GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CategoriaFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.CuentaCompartida", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.EliminacionGrupoFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.IntegranteFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.InvitacionFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.MovimientoFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.OperacionCaja", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaPrivadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasFamiliares.PresupuestoFamiliar", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.AporteMeta", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AportadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.MetaAhorro", null)
                        .WithMany()
                        .HasForeignKey("MetaAhorroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.MetaAhorro", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasFamiliares.GrupoFamiliar", null)
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Movimiento", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.MovimientoRecurrente", null)
                        .WithMany()
                        .HasForeignKey("RecurrenciaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.MovimientoRecurrente", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.Presupuesto", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.FinanzasPersonales.TarjetaCredito", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.DesafioOtp", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.EliminacionPerfil", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.PreferenciasUsuario", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithOne("Preferencias")
                        .HasForeignKey("FinanzasInteligentes.Dominio.Identidad.PreferenciasUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.RecuperacionContrasena", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.Sesion", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.VerificacionOtp", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.DesafioOtp", null)
                        .WithOne()
                        .HasForeignKey("FinanzasInteligentes.Dominio.Identidad.VerificacionOtp", "DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Suscripciones.Suscripcion", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.Suscripciones.PlanSuscripcion", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.Identidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovimientoCategoria", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Categoria", null)
                        .WithMany()
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Movimiento", null)
                        .WithMany()
                        .HasForeignKey("movimiento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PresupuestoCategoria", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Categoria", null)
                        .WithMany()
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Presupuesto", null)
                        .WithMany()
                        .HasForeignKey("presupuesto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecurrenciaCategoria", b =>
                {
                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.Categoria", null)
                        .WithMany()
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasInteligentes.Dominio.FinanzasPersonales.MovimientoRecurrente", null)
                        .WithMany()
                        .HasForeignKey("recurrencia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanzasInteligentes.Dominio.Identidad.Usuario", b =>
                {
                    b.Navigation("Preferencias")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
